version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - db
  classifier:
    image: jwjralph/deepdetect
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
